### ISSUE TITLE
ERROR dev-qt/qtsql-5.9.6-r1

### ISSUE THREAD

**Issue by johndoe71rus** [iDarkTemplar/dt-overlay-patches#1]
Hi.
i use this overay to lxqt 0.13
i try update sustem Calculate Linux and get error 
* ERROR: dev-qt/qtsql-5.9.6-r1::dt-overlay-patches failed (compile phase):
*   emake failed

https://paste.ubuntu.com/p/JzQdJzThWQ/ emerge --info
http://pastebin.calculate-linux.ru/ru/show/64849 build log

**Comment by johndoe71rus** [comment]
so i can't update 3 packages because they depenceses.
(U) dev-qt/qthelp-5.9.6 
(U) dev-qt/qtsql-5.9.6-r1
(U) dev-qt/qtwebkit-5.9.1-r1

https://paste.ubuntu.com/p/sVNCGJmDWX/

**Comment by iDarkTemplar** [comment]
Hi. Sorry for taking long time to respond. It looks like I didn't get a notification by default on new issue.

As for building qtsql, unfortunately, currently there it's not possible to build qtsql with enabled USE-flags `postgres` or `freetds` for non-native ABI because there are no multilib versions of packages `dev-db/freetds` and `dev-db/postgresql` in official Gentoo repository or my overlays.

Unfortunately, I don't know how to express these restrictions properly with USE-flag restrictions, due to that qtsql fails at build time under these conditions. If you know how to do it, I'd gladly move this check to dependencies calculation phase.

If you don't need `dev-qt/*` packages from this repository, you may just mask all of them adding a line like following one into you `package.mask` files (assuming this repository is named `dt-overlay-patches`):
`dev-qt/*::dt-overlay-patches`

If you want to use packages `dev-qt/*` from this overlay, you either need to disable `postgres` USE-flag for `qtsql`, or you may disable 32-bit build for `qtsql` and packages depending on it (`qthelp` and `qtwebkit`). Or you may disable multilib for all packages from `dev-qt/*`.

And AFAIK lxqt-0.13 is present in main Gentoo tree now.

Edit: fixed hidden special characters

**Comment by iDarkTemplar** [comment]
Following change should ensure that it fails on pkg_pretend phase:
https://github.com/iDarkTemplar/dt-overlay-patches/commit/1a6177feb7d976dc81c2a34bd4498061594f8f4f

**Comment by johndoe71rus** [comment]
yes, i switch to lxqt 0.13 from main Gentoo tree
